name: Environment demo

on:
  workflow_dispatch:

jobs:
  environment-demo:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: staging

    steps:
      - name: Mostrar vari√°vel de ambiente
        run: |
          echo "Deploy: $DEPLOY_ENV"
