name: Matrix strategy

on:
  workflow_dispatch:

jobs:
  matrix-strategy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 11, 17 ]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v6

      - name: Setup Java (${{matrix.java}})
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{matrix.java}}
          cache: 'maven'

      - name: Versão do Java
        run: |
          echo "Versão do Java: ${{matrix.java}}"

      - name: Maven build
        run: mvn -B clean install
