name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v6

      - name: Setup Java (21)
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Compila o projeto
        run: |
          echo "::debug::Iniciando compilação"
          mvn -B clean compile
          echo "::debug::Compilação concluída com sucesso"

      - name: Executa os testes
        run: |
          echo "::debug::Executando testes"
          mvn -B clean test
          echo "::debug::Testes executados com sucesso"

      - name: Build com maven
        run: |
          echo "::debug::Iniciando build"
          mvn -B clean install
          echo "::debug::Build realizado com sucesso"
