name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v6

      - name: Setup Java (21)
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Compila o projeto
        run: mvn -B clean compile

      - name: Executa os testes
        run: mvn -B clean test

      - name: Build com maven
        run: mvn -B clean install
