name: Secret demo

on:
  workflow_dispatch:

jobs:
  secret-demo:
    runs-on: ubuntu-latest

    environment: secret

    steps:
      - name: Secret configurado
        run: echo "API_KEY configurada"

      - name: Valida a API KEY
        env:
          API_KEY: ${{secrets.API_KEY}}
        run: |
          if [ -n "$API_KEY" ]; then
            echo "API_KEY válida!"
          else
            echo "API_KEY não encontrada!"
          fi
